### ISSUE TITLE
CalDav support

### ISSUE THREAD

**Issue by tombh** [robertwt7/meetsy#51]
Just saw this on Hacer News. It looks great. Would you ever be interested in CalDav support?

**Comment by robertwt7** [comment]
Hello @tombh ! 

Thanks for your time to check out the project :)

When you say CalDav support, do you mean implementing it on the data that we have? At the moment we don't save, or manage user's calendar or events. Meetsy is merely using user's google data to fetch events, which allows them to have more information before creating new events. Afterwards, the data is also saved in the user's google calendar once the invitee accepted the invite. 

So CalDav support will be a lot to implement since I don't even have user's data at the moment.

Would be good for future reference though

**Comment by tombh** [comment]
Maybe I misunderstand something. Basically I just want to know if you ever plan to support services apart from Google? CalDav is just the open standard for calendar data, it's not a REST API, but neither do I believe you'd need to store user data in order to read and write events to a CalDav calendar.

**Comment by robertwt7** [comment]
For sure!

At the moment the idea of using google is to integrate user's events so they have informed decision, however I would also like to make it open. For instance to allow guest booking as a start #52, then I will plan out further on the identity area, calendar data etc. 

Haven't had a proper roadmap yet but I'll put it on top of my list
